services:
    btn_page.provider.node_content:
        class: Btn\PageBundle\Provider\NodeContentProvider
        arguments:
            router: '@router'
            em:     '@doctrine.orm.entity_manager'
