parameters:
    btn_page.provider.node_content.class: Btn\PageBundle\Provider\NodeContentProvider

services:
    btn_page.provider.node_content:
        class: %btn_page.provider.node_content.class%
        arguments:
            entityProvider: '@btn_page.provider.page'
