parameters:
    btn_page.provider.page_node_content.class: Btn\PageBundle\Provider\PageNodeContentProvider

services:
    btn_page.provider.page_node_content:
        class: %btn_page.provider.page_node_content.class%
        arguments:
            configuration: %btn_page.node_content_provider.page%
        tags:
            - { name: btn_node.content_provider }
