services:
    #add link to the CP top menu
    btn_page.menu_navbar.page_item:
        class: %btn_admin.menu_item.class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: [@request, 'btn_page.menu_navbar.page_item.label', 'btn_page_pagecontrol_index', [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar }
